### ISSUE TITLE
Pushes are checked multiple times if they have tags

### ISSUE THREAD

**Issue by jsoref** [check-spelling/examples#2]
### Scenario
If you have the following in your yaml:
```yaml
name: Spell checking

on: [push]
```

#### Step
You push a commit that is both the tip of a branch and tagged

#### Results
Your check will run twice.

### Recommended best practice

```yaml
name: Spell checking

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
```
